d_customer:
    constraints:
        not_null:
            - customer_id
        unique:
            - customer_id
d_sku:
    constraints:
        not_null:
            - sku_id
            - product_id
        unique:
            - sku_id
d_campaign:
    constraints:
        not_null:
            - campaign_key
            - campaign_name
            - campaign_channel_name
        unique:
            - campaign_key
f_order:
    constraints:
        not_null:
            - customer_id
            - product_id
            - campaign_key
    relationships:
            - {from: customer_id, to: ref('d_customer'), field: customer_id}
            - {from: sku_id, to: ref('d_sku'), field: sku_id}
            - {from: campaign_key, to: ref('d_campaign'), field: campaign_key}
    dbt_utils.recency:
            - {field: order_date, datepart: day, interval: 1}
